apiVersion: v1
kind: Pod
metadata:
  name: webapp-credentials
  labels:
    app: webapp-credentials
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'injector-role'
    vault.hashicorp.com/agent-inject-secret-credentials.txt: 'kvv2/data/webapp'
    vault.hashicorp.com/auth-path: "auth/injector"
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
